version: "3"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db-data: