version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: transfeera
      POSTGRES_PASSWORD: transfeera.t3st
      POSTGRES_DB: transfeera
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
volumes:
  db-data:
